options:
  coin_type:
    type: string
    default: "litecoin"
    description: The crypto currency you wish to mine.(e.g. bitcoin, litecoin, dogecoin)
  mpos_user:
    type: string
    default: "coinrpcuser"
    description: This is for user name configuration.
  mpos_pass:
    type: string
    default: "13rUVnQTFkw7k7Pz4iXWawxQgkYYKUeXHUroSFnSiDB"
    description: This is for rpc user password configuration.
  db_name:
    type: string
    default: "mind"
    description:
  db_user:
    type: string
    default: "root"
    description:
  db_pass:
    type: string
    default: "shizzlenizzle"
    description:
  rpc_port:
    type: int
    default: 19323
    description:
  rpc_timeout:
    type: int
    default: 30
    description:
  alerts_email:
    type: string
    default: "user@support.com"
    description: This is for bicoind alerts.
  block_hash:
    type: boolean
    default: true
    description:
  pool_target:
    type: int
    default: 32
    description:
  base_dir:
    type: string
    default: "/opt"
    description: Base directory where files will be installed from or to. (Leave the trailing"/" off)
  db_port:
    type: int
    default: 3306
    description:
  coin_url:
    type: string
    default: "http://www.litecoin.org"
    description:
  coin_target:
    type: int
    default: 150
    description:
  coin_diff_change_target:
    type: int
    default: 2016
    description:
  payout_system:
    type: string
    default: "prop"
    description:
  db_host:
    type: string
    default: "localhost"
    description:
  rpc_host:
    type: string
    default: "localhost"
    description:
  stratum_url:
    type: string
    default: ""
    description:
  stratum_port:
    type: int
    default: 3333
    description:
  price_url:
    type: string
    default: "https://btc-e.com"
    description:
  price_target:
    type: string
    default: "/api/2/ltc_usd/ticker"
    description:
  price_currency:
    type: string
    default: "USD"
    description:
  currency_abv:
    type: string
    default: "LTC"
    description:
  ap_min:
    type: int
    default: 1
    description:
  ap_max:
    type: int
    default: 250
    description:
  pps_reward:
    type: int
    default: 4000000
    description:
  pplns_shares:
    type: int
    default: 50
    description: 
  host_id:
    type: string
    default: "localhost"
    description:
