#!/bin/bash

coin_type=`config-get coin_type`
currency_abv=`config-get currency_abv`
base_dir=`config-get base_dir`

cd ${base_dir}

service apache2 start || service apache2 restart

[[ -x /usr/bin/${coin_type}d ]] || sudo -u ubuntu -i sudo nohup ${coin_type}d -daemon

cd stratum-mining-${currency_abv}
sudo twistd -y launcher.tac
cd ..
