#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
# i.e. 'service apache2 start'


coin_type=`config-get coin_type`
base_dir=`config-get base_dir`

cd ${base_dir}

sudo nohup ${coin_type}d -conf=/home/ubuntu/.${coin_type}/${coin_type}.conf -daemon

cd stratum-mining
sudo twistd -y launcher.tac
cd ..
