#!/bin/bash

coin_type=`config-get coin_type`
base_dir=`config-get base_dir`

cd ${base_dir}

service apache2 start || service apache2 restart

sudo nohup ${coin_type}d -conf=/home/ubuntu/.${coin_type}/${coin_type}.conf -daemon

cd stratum-mining
sudo twistd -y launcher.tac
cd ..
